### ISSUE TITLE
Bot owner not working properly

### ISSUE THREAD

**Issue by guinhx** [LukeIsHereToDevelop/opcommands#4]
I can't start my bot because got an error while starting.

[Code I have writed](https://prnt.sc/GHte38ZmCtmd)

C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\opcommands\src\handlers\Command.js:43
              _this.client.msgs.notifyOwnerMessage(user);
                                                   ^
ReferenceError: user is not defined
    at Client.<anonymous> (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\opcommands\src\handlers\Command.js:43:52)
    at Client.emit (node:events:402:35)
    at Client.emit (node:domain:475:12)
    at WebSocketManager.triggerClientReady (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:390:28)
    at WebSocketShard.emit (node:domain:475:12)
    at WebSocketShard.checkReady (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:475:12)
    at WebSocketShard.onPacket (C:\Users\sarac\Documents\Workspaces\Node\pixey-bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:447:16)

**Comment by LukeIsHereToDevelop** [comment]
Hmm, I think @MilleniumModsSources forgot to define the user variable. I'm going to fix it right now, set the `notifyOwner` option to `false` at the moment. Thank you very much for letting me know!

**Comment by LukeIsHereToDevelop** [comment]
I finally fixed it! Forgive me for the long wait but I had some IRL things to do. Thanks for telling me!
