### ISSUE TITLE
owner send issue

### ISSUE THREAD

**Issue by ThunderRock13** [LukeIsHereToDevelop/opcommands#5]
_this.client.msgs.notifyOwnerMessage(user);
                                                   ^

ReferenceError: user is not defined
    at Client.<anonymous> (C:\Users\Noah\WebstormProjects\discordbot\node_modules\opcommands\src\handlers\Command.js:43:52)
    at Client.emit (node:events:390:28)
    at WebSocketManager.triggerClientReady (C:\Users\Noah\WebstormProjects\discordbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:17)
    at WebSocketManager.checkShardsReady (C:\Users\Noah\WebstormProjects\discordbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:367:10)
    at WebSocketShard.<anonymous> (C:\Users\Noah\WebstormProjects\discordbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:189:14)
    at WebSocketShard.emit (node:events:390:28)
    at Timeout._onTimeout (C:\Users\Noah\WebstormProjects\discordbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:499:14)
    at listOnTimeout (node:internal/timers:557:17)

I get this when running the owner command. When I put it to false I get this

DiscordAPIError[50035]: Invalid Form Body
0.options[1].type[NUMBER_TYPE_COERCE]: Value "ROLE" is not int.
    at SequentialHandler.runRequest (C:\Users\Noah\WebstormProjects\discordbot\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (C:\Users\Noah\WebstormProjects\discordbot\node_modules\@discordjs\rest\dist\lib\handlers\SequentialHandler.js:99:20)
    at async C:\Users\Noah\WebstormProjects\discordbot\node_modules\opcommands\src\handlers\Command.js:52:25 {
  rawError: {
    code: 50035,
    errors: { '0': [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/704395654285361193/guilds/785573887789891594/commands'
}

**Comment by ThunderRock13** [comment]
I fixed it by removing these two lines in Command.js

if (_this.client.msgs.notifyOwnerMessage) {
              //_this.client.msgs.notifyOwnerMessage(user);
            } else {
              // if there isn't any message, it uses a default one

            };

**Comment by LukeIsHereToDevelop** [comment]
Hello! I am already in the know of the undefined user variable. I'll fix it ASAP. Regarding the error you get when you set the setting to false, it should be an error of your code.

**Comment by LukeIsHereToDevelop** [comment]
I just fixed it. Check the new version and thanks for telling me!
